sudo: required
services:
  - docker
install: false
script: docker run -v $(pwd)/install.sh:/install.sh --rm -it ubuntu /bin/bash -c "apt-get update && apt-get install -y && wget sudo && chmod +x /install.sh && /install.sh"
